FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime

COPY requirements.txt /tmp/requirements.txt

RUN apt update -y && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt && \
    rm /tmp/requirements.txt && \
    apt install git -y

WORKDIR /projects

ENTRYPOINT [ "bash" ]
