FROM python:3.10-bullseye

COPY requirements.txt /tmp/requirements.txt

RUN apt update -y && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt && \
    rm /tmp/requirements.txt

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

WORKDIR /projects

ENTRYPOINT [ "bash" ]