name: Build and push image

on:
  workflow_run:
    workflows: 
      - CI
    branches: 
      - main
    types: 
      - completed

jobs:         
  build_image:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push
        run: make TAG=0.0.1 

      - name: build and push latest
        run: make TAG=latest 