name: Build and push image

on:
  workflow_run:
    workflows: 
      - CI
    branches: 
      - main
    types: 
      - completed

jobs:
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: shellcheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          severity: error
          scandir: './'
          format: tty
          
  build_image:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push
        run: make TAG=0.0.1 

      - name: build and push latest
        run: make TAG=latest 